#-- name: Build MelonLoader Mod

on:
  push:
    branches: [ main ] 
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1

    - name: Restore NuGet Packages
      run: nuget restore Simple.csproj

    - name: Build Solution
      run: msbuild Simple.csproj /p:Configuration=Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: SealeenDevMenu-DLL
        path: bin/Release/Sealeen.dll
#--]
